/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyquanhatkaraoke.application;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.CaLamViecDAO;
import model.dao.DAOFactory;
import model.dao.LichDangKyDAO;
import model.entities.CaLamViec;
import model.entities.LichDangKy;
import model.entities.NguoiDung;

/**
 *
 * @author thuongptitdev
 */
public class DangKyLichFrm extends javax.swing.JFrame {

    /**
     * Creates new form DangKyLichFrm
     */
    NguoiDung nguoiDung;
    List<CaLamViec> listCa;
    List<LichDangKy> listLichDangKys;
    public DangKyLichFrm(NguoiDung nguoiDung) {
        initComponents();
        displayChoice();
        this.nguoiDung = nguoiDung;
        listLichDangKy();
    }

    public void displayChoice() {
        try {
            CaLamViecDAO calamviecdao = DAOFactory.createCaLamViecDAO();
            listCa = calamviecdao.fillAll();
            for (CaLamViec ca : listCa) {
                String a = ca.getGioBatDau() + "h";
                if (ca.getPhutBatDau() != 0) {
                    a += ca.getPhutBatDau() + "p";
                }
                String b = ca.getGioKetThuc() + "h";
                if (ca.getPhutKetThuc() != 0) {
                    b += ca.getPhutKetThuc() + "p";
                }
                choice1.add(ca.getTen() + " từ " + a + " đến " + b);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void listLichDangKy(){
        try{
            LichDangKyDAO lichdangkydao = DAOFactory.createLichDangKyDAO();
            listLichDangKys = lichdangkydao.fillAllByIdNguoiDung(this.nguoiDung.getId());
            String[] tblHead = {"Tên ca", "Ngày",  "Giờ bắt đầu", "Giờ kết thúc","Trạng thái"};
            DefaultTableModel model = new DefaultTableModel(tblHead, 0);
            DefaultTableModel model2 = new DefaultTableModel(tblHead, 0);
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
            for (LichDangKy lich : listLichDangKys) {
                CaLamViec ca = lich.getCaLamViec();
                List<String> list = new ArrayList<String>();
                list.add(ca.getTen());
                list.add(formatter.format(lich.getNgay()));
                String a = ca.getGioBatDau() + "h";
                if (ca.getPhutBatDau() != 0) {
                    a += ca.getPhutBatDau() + "p";
                }
                list.add(a);
                String b = ca.getGioKetThuc() + "h";
                if (ca.getPhutKetThuc() != 0) {
                    b += ca.getPhutKetThuc() + "p";
                }
                list.add(b);
                list.add(lich.getTrangthai());
                if(lich.getTrangthai().equals("Da duyet")){
                    model2.addRow(list.toArray());
                }
                model.addRow(list.toArray());
            }
            jTable1.setModel(model);
            jTable2.setModel(model2);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Chọn ngày :");

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Chọn ca làm việc :");

        jButton1.setText("Đăng kí");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Đăng kí lịch", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lịch làm việc", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
        Date test = jXDatePicker1.getDate();
        System.out.println("");
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date ngay = jXDatePicker1.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy"); 
        if(ngay == null){
            failedMessage("Bạn phải chọn ngày đi làm");
            return;
        }else if(ngay.getTime() < new Date().getTime() && !formatter.format(ngay).equals(formatter.format(new Date()))){
            failedMessage("Thời gian không hợp lệ");
            return;
        }

        
        int index = choice1.getSelectedIndex();
        if(index < 0){
            failedMessage("Bạn phải chọn ca làm việc");
            return;
        }
        CaLamViec ca = listCa.get(index);
        LichDangKy lichdangky = new LichDangKy();
        lichdangky.setNguoiDung(nguoiDung);
        lichdangky.setNgay(ngay);
        lichdangky.setCaLamViec(ca);
        lichdangky.setTrangthai("Cho duyet");
        try{
            LichDangKyDAO lichdangkydao = DAOFactory.createLichDangKyDAO();
            lichdangkydao.insert(lichdangky);
            failedMessage("Thêm lịch đăng kí thành công");
            listLichDangKy();
        }catch(Exception ex){
            ex.printStackTrace();
            failedMessage("Thêm lịch đăng kí thất bại");
        }
        System.out.println("");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void failedMessage(String errormsg) {
        JOptionPane.showMessageDialog(null, errormsg); // give user feedback
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
