/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyquanhatkaraoke.application;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.dao.DAOFactory;
import model.dao.LichDangKyDAO;
import model.dao.LichLamViecDAO;
import model.entities.CaLamViec;
import model.entities.LichDangKy;
import model.entities.LichLamViec;
import model.entities.NguoiDung;
import model.entities.QuanLy;

/**
 *
 * @author thuongptitdev
 */
public class DuyetDangKyLichFrm extends javax.swing.JFrame {

    /**
     * Creates new form DuyetDangKyLichFrm
     */
    QuanLy quanLy;
    List<LichDangKy> listLichDangKys;
    List<LichDangKy> listLichDangKysChuaDuyet;
    LichDangKy seleLichDangKy;
    public DuyetDangKyLichFrm(QuanLy quanLy) {
        initComponents();
        this.quanLy =  quanLy;
        listLichDangKy();
               jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                // do some actions here, for example
                int selectrow = jTable1.getSelectedRow();
                if(selectrow == -1){
                    return;
                }
                seleLichDangKy = listLichDangKysChuaDuyet.get(selectrow);
                jButton1.setVisible(true);
                // print first column value from selected row
                // System.out.println(table.getValueAt(table.getSelectedRow(), 0).toString());
            }
        });
    }
    
    
    private void listLichDangKy(){
        try{
            jButton1.setVisible(false);
            seleLichDangKy = null;
            LichDangKyDAO lichdangkydao = DAOFactory.createLichDangKyDAO();
            listLichDangKys = lichdangkydao.fillAll();
            listLichDangKysChuaDuyet = new ArrayList<LichDangKy>();
            String[] tblHead = {"Tên nhân viên","Chức vụ","Tên ca", "Ngày",  "Giờ bắt đầu", "Giờ kết thúc","Trạng thái"};
            DefaultTableModel model = new DefaultTableModel(tblHead, 0);
            DefaultTableModel model2 = new DefaultTableModel(tblHead, 0);
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
            for (LichDangKy lich : listLichDangKys) {
                CaLamViec ca = lich.getCaLamViec();
                List<String> list = new ArrayList<String>();
                list.add(lich.getNguoiDung().getTen());
                String chucvu = "N/A";
                if(lich.getNguoiDung().getRole() == NguoiDung.ROLE.LE_TAN){
                    chucvu = "Lễ tân";
                }else if(lich.getNguoiDung().getRole() == NguoiDung.ROLE.PHUC_VU){
                    chucvu = "Phục vụ";
                }
                list.add(chucvu);
                list.add(ca.getTen());
                list.add(formatter.format(lich.getNgay()));
                String a = ca.getGioBatDau() + "h";
                if (ca.getPhutBatDau() != 0) {
                    a += ca.getPhutBatDau() + "p";
                }
                list.add(a);
                String b = ca.getGioKetThuc() + "h";
                if (ca.getPhutKetThuc() != 0) {
                    b += ca.getPhutKetThuc() + "p";
                }
                list.add(b);
                list.add(lich.getTrangthai());
                if(lich.getTrangthai().equals("Da duyet")){
                    model2.addRow(list.toArray());
                }else if(lich.getTrangthai().equals("Cho duyet")){
                    model.addRow(list.toArray());
                    listLichDangKysChuaDuyet.add(lich);
                }
                
            }
            jTable1.setModel(model);
            jTable2.setModel(model2);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Duyệt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("chưa duyệt", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("đã duyệt", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(seleLichDangKy == null){
            failedMessage("Vui lòng chọn một lịch đăng kí trước");
            return;
        }
        try{
            LichLamViecDAO dao = DAOFactory.createLichLamViecDAO();
            LichLamViec lamviec = new LichLamViec();
            lamviec.setLichDangKy(seleLichDangKy);
            dao.accept(lamviec);
            failedMessage("Thành công");
            listLichDangKy();
        }catch(Exception ex){
            ex.printStackTrace();
            failedMessage("Thất bại");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void failedMessage(String errormsg) {
        JOptionPane.showMessageDialog(null, errormsg); // give user feedback
    }
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
